### ISSUE TITLE
Can you share the dockerfile for v5.0 with head plugin?

### ISSUE THREAD

**Issue by pulkitsinghal** [mobz/elasticsearch-head#347]
I could not figure out where to find the `Dockerfile` for the image: `mobz/elasticsearch-head:5`

I am interested in taking a peek at how you've put it all together.

I tried myself but no luck:

1. `docker-compose.yml` file:

```
version: '2'
services:
  es_v5:
    image: elasticsearch:5
    ports:
     - "9203:9200"
    volumes:
     - .:/apps
    entrypoint: /apps/docker-entrypoint-es5-plugins.sh
  es_head:
    image: node:7.10.0
    ports:
      - "9100:9100"
    working_dir: /apps/head
    volumes:
     - ./head:/apps/head
     - ./docker-entrypoint-es5-head.sh:/apps/docker-entrypoint-es5-head.sh
    entrypoint: /apps/docker-entrypoint-es5-head.sh
    depends_on:
      - es_v5
```
2. `docker-entrypoint-es5-plugins.sh` file

```
#!/bin/bash
echo 'http.cors.enabled: true' >> /etc/elasticsearch/elasticsearch.yml
echo 'http.cors.allow-origin: "*"' >> /etc/elasticsearch/elasticsearch.yml
cat /etc/elasticsearch/elasticsearch.yml
exec /docker-entrypoint.sh elasticsearch
```
3. `docker-entrypoint-es5-head.sh` file
```
#!/bin/bash
# start script needs `grunt` which is in devDependencies
npm install
exec npm run start
```

4. But when I browse to `localhost:9100` and ask it to connect with `localhost:9203` ... nothing happens. cc @aquid
