### ISSUE TITLE
support for opensearch out of the box

### ISSUE THREAD

**Issue by johndpope** [mobz/elasticsearch-head#481]
https://github.com/johndpope/elasticfeeds/blob/3e6bbf8b6a2a937b5b6131f75f08e082cbd4671b/elasticsearch_docker/docker-compose.yml

```yaml

version: '2.2'

services:
  os01:
    image: opensearchproject/opensearch:2.2.0
    container_name: os01
    environment:
      - node.name=os01
      - cluster.name=os-docker-cluster
      - discovery.seed_hosts=os02,os03
      - cluster.initial_master_nodes=os01,os02,os03
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/Users/johndpope/opensearch/data
    ports:
      - 9200:9200
    networks:
      - opensearch

  os02:
    image: opensearchproject/opensearch:2.2.0
    container_name: os02
    environment:
      - node.name=os02
      - cluster.name=os-docker-cluster
      - discovery.seed_hosts=os01,os03
      - cluster.initial_master_nodes=os01,os02,os03
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/Users/johndpope/opensearch/data
    networks:
      - opensearch

  os03:
    image: opensearchproject/opensearch:2.2.0
    container_name: os03
    environment:
      - node.name=os03
      - cluster.name=os-docker-cluster
      - discovery.seed_hosts=os01,os02
      - cluster.initial_master_nodes=os01,os02,os03
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/Users/johndpope/opensearch/data
    networks:
      - opensearch

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  opensearch:
    driver: bridge
```
